name: 🖼️ Generate a New Screenshot of a RoundUp

on:
  workflow_call:
    inputs:
      issue_no:
        required: true
        type: string
      issue_id:
        required: true
        type: string
      base_url:
        required: true
        type: string
      do_push:
        default: true
        type: boolean
    outputs: 
      base_url: 
          description: "The Base URL of the site"
          value: ${{ jobs.build.outputs.base_url }}
  workflow_dispatch:
    inputs:
      issue_no:
        type: string
        required: true
      base_url:
        description: "The Base URL of the site"
        default: "https://roundup.stlgame.dev"
        type: string
      do_push:
        type: boolean
        default: false
        description: "Leave OFF"
        
permissions: write-all

concurrency:
    group: "pages"
    cancel-in-progress: false

defaults:
    run:
      shell: bash

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps: 
        -   name: Checkout
            uses: actions/checkout@v4
            with: 
                submodules: recursive
                fetch-depth: 0
        -   name: Screenshot
            id: screenshot
            uses: karol-brejna-i/webpage-screenshot-action@v1.1.2
            with:
              url: "${{ inputs.base_url }}/issue-${{ inputs.issue_no }}/?ss=true"
              output: "issue-${{ inputs.issue_no }}.png"
              mode: page

        -   name: Return Image
            if: ${{ ! inputs.do_push }}
            uses: actions/upload-artifact@v4
            with:
              name: simple-screenshot
              path: ${{ github.workspace }}/*.png

        -   name: Commit image
            if: ${{ inputs.do_push }} 
            run: |
                git pull
                mkdir -p screenshots
                mv -f ${{ github.workspace }}/issue-${{ inputs.issue_no }}.png screenshots/issue-${{inputs.issue_no }}.png
                git config --global user.name "GitHub Actions"
                git config --global user.email "no-reply@github.com"
                git tag generated-screenshot-${{ inputs.issue_no }}
                git add screenshots/issue-${{ inputs.issue_no }}.png
                git commit -m "Update issue image ${{ inputs.issue_no }}"
                git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
                git push --follow-tags 
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
  
