name: ▶ Generate or Regenerate a RoundUp Issue!
run-name: Generate ${{ github.event.inputs.issue_type }} - by @${{ github.actor }}

on:
    workflow_dispatch:
        inputs:
            issue_type:
                type: choice
                required: true
                description: "Which issue to build"
                default: "next-roundup"
                options:
                    -   "next-roundup"
                    -   "test"
                    -   "regenerate"
            issue_no:
                type: string
                description: "Which issue no to take a build"
                default: '-1'

permissions: write-all

concurrency:
    group: ${{ github.repository }}-generate-roundup
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:

    prepare:
        runs-on: ubuntu-latest
        outputs:
            final-issue-no: ${{ steps.set-value.outputs.issue_no }}
        steps:
            -   name: Set issue_no dynamically
                id: set-value
                run: |
                    if [ "${{ github.event.inputs.issue_type }}" = "regenerate" ]; then
                        echo "issue_no=${{ github.event.inputs.issue_no }}" >> $GITHUB_OUTPUT
                    else
                        echo "issue_no=${{ github.event.inputs.issue_type }}" >> $GITHUB_OUTPUT
                    fi

    generate:
        needs: prepare
        uses: ./.github/workflows/build-issue.yaml
        with:
            issue_no: ${{ needs.prepare.outputs.final-issue-no }}
        secrets: inherit

    build:
        uses: ./.github/workflows/hugo-build.yaml
        needs: generate

    screenshot:
        needs: [generate, build]
        if: ${{ github.event.inputs.issue_type != 'test' }}
        uses: ./.github/workflows/generate-screenshot.yaml
        with:
            issue_no: ${{ needs.generate.outputs.issue_no }}
            base_url: ${{ needs.build.outputs.base_url }}

    newsletter:
        needs: [generate, build, screenshot]
        if: ${{ github.event.inputs.issue_type == 'next-roundup' }}
        uses: ./.github/workflows/roundup-email.yaml
        with:
            issue_no: ${{ needs.generate.outputs.issue_no }}
            base_url: ${{ needs.build.outputs.base_url }}
        secrets: inherit

    share:
        runs-on: ubuntu-latest
        needs: [screenshot, generate, build, newsletter]
        if: ${{ github.event.inputs.issue_type == 'next-roundup' }}
        steps:
            
            -   name: Bsky's
                uses: myConsciousness/bluesky-post@v5
                with: 
                    text:
                        St Louis Game Developer RoundUp Issue № ${{  needs.generate.outputs.issue_no }} is out!

                        ${{ needs.build.outputs.base_url }}/issue-${{  needs.generate.outputs.issue_no }}/
                    link-preview-url: ${{ needs.build.outputs.base_url }}/issue-${{  needs.generate.outputs.issue_no }}/
                    identifier: "axolstudio.com"
                    password: ${{ secrets.BLUESKY_PASSWORD }}
            -   name: Axol Discord
                uses: Ilshidur/action-discord@master
                env:
                    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                    DISCORD_EMBEDS: |
                        [
                            {
                                "title": "St Louis Game Developer RoundUp Issue № ${{ needs.generate.outputs.issue_no }}",
                                "url": "${{ needs.build.outputs.base_url }}/issue-${{ needs.generate.outputs.issue_no }}/",
                                "image": {
                                    "url": "https://raw.githubusercontent.com/AxolStudio/STLGameDevRoundUp/main/screenshots/issue-${{ needs.generate.outputs.issue_no }}.png"
                                }
                            }
                        ]
                with:
                    args: ":sparkles: St Louis Game Developer RoundUp Issue № ${{ needs.generate.outputs.issue_no }} is out!"
            -   name: STL Game Dev Discord
                uses: Ilshidur/action-discord@master
                env:
                    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_2 }}
                    DISCORD_EMBEDS: |
                        [
                            {
                                "title": "St Louis Game Developer RoundUp Issue № ${{ needs.generate.outputs.issue_no }}",
                                "url": "${{ needs.build.outputs.base_url }}/issue-${{ needs.generate.outputs.issue_no }}/",
                                "image": {
                                    "url": "https://raw.githubusercontent.com/AxolStudio/STLGameDevRoundUp/main/screenshots/issue-${{ needs.generate.outputs.issue_no }}.png"
                                }
                            }
                        ]
                with:
                    args: ":sparkles: St Louis Game Developer RoundUp Issue № ${{ needs.generate.outputs.issue_no }} is out!"

    finish:
        runs-on: ubuntu-latest
        needs: [screenshot, generate, build, newsletter]
        if: ${{ github.event.inputs.issue_type == 'next-roundup' }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Close Issue
                run: gh issue close ${{ needs.generate.outputs.issue_id }} -c "[Issue № ${{ needs.generate.outputs.issue_no }}](${{ needs.build.outputs.base_url }}/issue-${{ needs.generate.outputs.issue_no }}/) has been released!" -r completed
            -   name: Open New Issue
                run: |
                    new_no=$((${{ needs.generate.outputs.issue_no }}+1))
                    gh issue create -t "RoundUp Issue #$new_no" -b "To add to the next roundup, use the following format:
                    \`\`\`md
                    {category} short description with [link](/link/to/item)
                    \`\`\`

                    Which should generate the following:

                    {category} short description with [link](/link/to/item)

                    Use \`{!header}\` as the category for *only one comment* to set the header message for this RoundUp." -l "next-roundup" 
